spring.application.name=panterfitness

spring.profiles.default=supabase
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=7200000
panterfitness.demo.enabled=${PANTERFITNESS_DEMO_ENABLED:false}
