-- Pantera Fitness / panterfitness. Ejecutar una vez sobre un esquema sin estas tablas.
BEGIN;

CREATE TABLE public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL CONSTRAINT idx_usuarios_email UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(50) NOT NULL CHECK (rol IN ('CLIENTE','PROFESOR','ADMINISTRADOR')),
    estado_membresia VARCHAR(50) NOT NULL CHECK (estado_membresia IN ('ACTIVA','VENCIDA','SUSPENDIDA','PENDIENTE')),
    fecha_inicio_membresia DATE,
    fecha_vencimiento_membresia DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    qr_simulado VARCHAR(255) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.sectores_gimnasio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE CHECK (nombre IN ('MUSCULACION','SALA_CLASES')),
    capacidad_maxima INTEGER NOT NULL CHECK (capacidad_maxima > 0),
    ocupacion_actual INTEGER NOT NULL DEFAULT 0 CHECK (ocupacion_actual >= 0 AND ocupacion_actual <= capacidad_maxima),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.clases_gimnasio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(1000),
    profesor_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    sector VARCHAR(50) NOT NULL CHECK (sector IN ('MUSCULACION','SALA_CLASES')),
    cupo_maximo INTEGER NOT NULL CHECK (cupo_maximo > 0),
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.horarios_clase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clase_gimnasio_id BIGINT NOT NULL REFERENCES public.clases_gimnasio(id),
    dia_semana VARCHAR(50) NOT NULL CHECK (dia_semana IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO')),
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL CHECK (hora_fin > hora_inicio),
    cupo_maximo INTEGER NOT NULL CHECK (cupo_maximo > 0),
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    horario_clase_id BIGINT NOT NULL REFERENCES public.horarios_clase(id),
    estado_reserva VARCHAR(50) NOT NULL CHECK (estado_reserva IN ('CONFIRMADA','CANCELADA','EN_ESPERA','ASISTIDA','AUSENTE')),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cancelacion TIMESTAMP
);

CREATE TABLE public.lista_espera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    horario_clase_id BIGINT NOT NULL REFERENCES public.horarios_clase(id),
    fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    posicion INTEGER NOT NULL CHECK (posicion > 0),
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.asistencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    reserva_id BIGINT REFERENCES public.reservas(id),
    horario_clase_id BIGINT NOT NULL REFERENCES public.horarios_clase(id),
    fecha DATE NOT NULL,
    hora_programada TIME NOT NULL,
    hora_ingreso TIMESTAMP NOT NULL,
    estado_asistencia VARCHAR(50) NOT NULL CHECK (estado_asistencia IN ('ASISTIDA','AUSENTE','CANCELADA','PENDIENTE')),
    metodo_registro VARCHAR(50) NOT NULL CHECK (metodo_registro IN ('QR_SIMULADO'))
);

CREATE TABLE public.notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    titulo VARCHAR(255) NOT NULL,
    mensaje VARCHAR(1000) NOT NULL,
    tipo_notificacion VARCHAR(50) NOT NULL CHECK (tipo_notificacion IN ('RESERVA','CANCELACION','LISTA_ESPERA','RECORDATORIO','PENALIZACION','ALERTA','RUTINA','SISTEMA','QR')),
    estado_notificacion VARCHAR(50) NOT NULL CHECK (estado_notificacion IN ('NO_LEIDA','LEIDA')),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_usuarios_rol ON public.usuarios (rol);
CREATE INDEX idx_usuarios_estado_membresia ON public.usuarios (estado_membresia);
CREATE INDEX idx_clases_profesor ON public.clases_gimnasio (profesor_id);
CREATE INDEX idx_horarios_fecha ON public.horarios_clase (fecha);
CREATE INDEX idx_horarios_clase ON public.horarios_clase (clase_gimnasio_id);
CREATE INDEX idx_reservas_usuario ON public.reservas (usuario_id);
CREATE INDEX idx_reservas_horario ON public.reservas (horario_clase_id);
CREATE INDEX idx_reservas_estado ON public.reservas (estado_reserva);
CREATE INDEX idx_lista_espera_horario_activa ON public.lista_espera (horario_clase_id, activa);
CREATE INDEX idx_lista_espera_usuario ON public.lista_espera (usuario_id);
CREATE INDEX idx_asistencias_usuario ON public.asistencias (usuario_id);
CREATE INDEX idx_asistencias_horario ON public.asistencias (horario_clase_id);
CREATE INDEX idx_asistencias_reserva ON public.asistencias (reserva_id);
CREATE INDEX idx_notificaciones_usuario_estado ON public.notificaciones (usuario_id, estado_notificacion);

CREATE UNIQUE INDEX uq_reservas_usuario_horario_activa ON public.reservas (usuario_id, horario_clase_id)
    WHERE estado_reserva IN ('CONFIRMADA','EN_ESPERA','ASISTIDA','AUSENTE');
CREATE UNIQUE INDEX uq_lista_espera_usuario_horario_activa ON public.lista_espera (usuario_id, horario_clase_id)
    WHERE activa = TRUE;

-- Spring accede por JDBC como propietario de las tablas (postgres).
-- Sin policies publicas: la Data API no debe acceder a estos datos.
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.usuarios FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.usuarios_id_seq FROM PUBLIC, anon, authenticated;
ALTER TABLE public.sectores_gimnasio ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sectores_gimnasio FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.sectores_gimnasio_id_seq FROM PUBLIC, anon, authenticated;
ALTER TABLE public.clases_gimnasio ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.clases_gimnasio FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.clases_gimnasio_id_seq FROM PUBLIC, anon, authenticated;
ALTER TABLE public.horarios_clase ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.horarios_clase FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.horarios_clase_id_seq FROM PUBLIC, anon, authenticated;
ALTER TABLE public.reservas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.reservas FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.reservas_id_seq FROM PUBLIC, anon, authenticated;
ALTER TABLE public.lista_espera ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.lista_espera FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.lista_espera_id_seq FROM PUBLIC, anon, authenticated;
ALTER TABLE public.asistencias ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.asistencias FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.asistencias_id_seq FROM PUBLIC, anon, authenticated;
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.notificaciones FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.notificaciones_id_seq FROM PUBLIC, anon, authenticated;

COMMIT;

