-- Incremental: ejecutar después de 001 en el proyecto existente. Conserva todos los datos.
BEGIN;

ALTER TABLE public.asistencias ADD COLUMN penalizacion_procesada BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.asistencias ALTER COLUMN hora_ingreso DROP NOT NULL;
ALTER TABLE public.asistencias DROP CONSTRAINT asistencias_metodo_registro_check;
ALTER TABLE public.asistencias ADD CONSTRAINT asistencias_metodo_registro_check
 CHECK (metodo_registro IN ('QR_SIMULADO','MANUAL','AUTOMATICO'));

CREATE TABLE public.penalizaciones (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
 motivo VARCHAR(1000) NOT NULL,
 fecha_inicio DATE NOT NULL,
 fecha_fin DATE NOT NULL CHECK (fecha_fin >= fecha_inicio),
 estado VARCHAR(50) NOT NULL CHECK (estado IN ('ACTIVA','FINALIZADA','CANCELADA'))
);
CREATE INDEX idx_penalizaciones_usuario_vigencia ON public.penalizaciones(usuario_id, estado, fecha_inicio, fecha_fin);

CREATE TABLE public.ejercicios (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(255) NOT NULL,
 descripcion VARCHAR(1000)
);
CREATE UNIQUE INDEX uq_ejercicios_nombre ON public.ejercicios(lower(nombre));

CREATE TABLE public.rutinas (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(255) NOT NULL,
 descripcion VARCHAR(1000),
 profesor_id BIGINT NOT NULL REFERENCES public.usuarios(id),
 cliente_id BIGINT NOT NULL REFERENCES public.usuarios(id),
 estado VARCHAR(50) NOT NULL CHECK (estado IN ('ACTIVA','FINALIZADA','PAUSADA'))
);
CREATE INDEX idx_rutinas_profesor ON public.rutinas(profesor_id);
CREATE INDEX idx_rutinas_cliente ON public.rutinas(cliente_id);

CREATE TABLE public.rutina_ejercicios (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 rutina_id BIGINT NOT NULL REFERENCES public.rutinas(id) ON DELETE CASCADE,
 ejercicio_id BIGINT NOT NULL REFERENCES public.ejercicios(id),
 series INTEGER NOT NULL CHECK (series > 0),
 repeticiones INTEGER NOT NULL CHECK (repeticiones > 0),
 peso_sugerido NUMERIC(10,2) CHECK (peso_sugerido >= 0),
 descanso INTEGER NOT NULL CHECK (descanso >= 0),
 orden INTEGER NOT NULL CHECK (orden > 0)
);
CREATE INDEX idx_rutina_ejercicios_rutina_orden ON public.rutina_ejercicios(rutina_id, orden);

CREATE TABLE public.alertas (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 titulo VARCHAR(255) NOT NULL,
 descripcion VARCHAR(1000) NOT NULL,
 fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 activa BOOLEAN NOT NULL DEFAULT TRUE,
 prioridad VARCHAR(50) NOT NULL CHECK (prioridad IN ('BAJA','MEDIA','ALTA'))
);
CREATE INDEX idx_alertas_activa ON public.alertas(activa, fecha_creacion);

-- El frontend usa Spring/JWT. No se habilita acceso por la Data API de Supabase.
ALTER TABLE public.penalizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ejercicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutinas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutina_ejercicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alertas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.penalizaciones, public.ejercicios, public.rutinas, public.rutina_ejercicios, public.alertas FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.penalizaciones_id_seq, public.ejercicios_id_seq, public.rutinas_id_seq, public.rutina_ejercicios_id_seq, public.alertas_id_seq FROM PUBLIC, anon, authenticated;

COMMIT;
